### ISSUE TITLE
Users can create a post

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#1]
## 💰 Feature

User can create a post

## 🗒️ Notes
- First issue requires the HTML and CSS for the navbar and buttons that will be used through out the site 
- Requires a form with a title input, a tags select input (checkboxes), a textarea for the content, and a upload for the user to add an image.

## 🖼 Wireframe
![image](https://user-images.githubusercontent.com/71475689/103026040-e1c7fe00-4507-11eb-963e-b11bea182625.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/env/post`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Create a function that previews image for the user
- [x] Create a new database named "environmentPosts"
- [x] Refactor the component to fetch the data from the server.
- [x] Complete the component with an initial state and an event handler for handleSubmit
- [x] Complete event handler to update the state when user submits and resets the form
- [x] Update bootstrap version, ensure UI is organized 
- [x] Use bootstrap helper classes for margin, color, centering and borders
- [x] Validate that the tags data are being stored as an Array 
- [x] Change navbar font color
