### ISSUE TITLE
User can create an account

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#10]
## 💰 Feature

User can create an account

## 🗒️ Notes

This will require me to utilize a password hashing with argon2

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030788-57849780-4511-11eb-9d22-9172cd1833a3.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/api/auth/sign-up`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Complete the component with an initial state of firstName, lastName, username and password and an event handler for onChange and onSubmit
- [x] Create a hash route to direct to landing page
