### ISSUE TITLE
Users can sign in to their account

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#11]
## 💰 Feature

User can sign-in to their account

## 🗒️ Notes

This will require me to use a hashed password with argon2 and create a token

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030866-83078200-4511-11eb-9e20-b8647aa2b792.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/api/auth/sign-in`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Complete the component with an initial state of username and password and an event handler for handleChange and handleSubmit 
- [x] Include an event handler in app.jsx to handleSignIn
- [x] Update fetch request to included signed in users usersId
- [x] update hash routes that only allow users to view posts
- [x] Included token HTTP header with each fetch request
