### ISSUE TITLE
User can view a list of their posts

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#2]
## 💰 Feature

User can view a list of their posts

## 🗒️ Notes

This will require me to make a fetch request to get the data stored in the database. 

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103029751-50f52080-450f-11eb-923f-c43a6c9d8c13.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle GET requests at `/api/users-posts`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Create a hash to change page from the post form to the view post page
- [x] Use the join method to write tags array as a list with commas
- [x] Style navbar to improve UI
