### ISSUE TITLE
User can read a post

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#3]
## 💰 Feature

User can read a post by click on the post description

## 🗒️ Notes

This will require me to use props to render the corresponding data

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030376-85b5a780-4510-11eb-9a22-359a65cddaf4.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle GET requests at `/api/post/:postId/user/:userId`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Complete the component with an initial state of null and an event handler for rendering the page with the corresponding data 
- [x] Create a hash route to switch from viewing post details to viewing the post
