### ISSUE TITLE
Users can edit their posts

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#4]
## 💰 Feature

User can edit their post

## 🗒️ Notes

This will require me to 

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030143-09bb5f80-4510-11eb-93c9-7fb2667ad464.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle PUT requests at `/api/post/:postId/user/:userId`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Complete the component with an initial state of post and an event handler for onSubmit and onChange
