### ISSUE TITLE
Users can delete their posts

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#5]
## 💰 Feature

User can delete their posts

## 🗒️ Notes

This will require me to create a modal

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030460-b3025580-4510-11eb-8a18-b32660177189.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle DELETE requests at `/api/post/:postId/user/:userId`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Create a hash route that goes back to users-post page
- [x] Delete unnecessary code line
- [x] Re-style buttons using Bootstap btn class
