### ISSUE TITLE
User can view popular posts

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#6]
## 💰 Feature

User can view poplular posts

## 🗒️ Notes

This will require me to order the post by number of likes 

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030514-d200e780-4510-11eb-99da-fd4973aecc7d.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle GET requests at `/api/top-posts`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Complete the component with an initial state of post and likes and an event handler for a like
