### ISSUE TITLE
User can like posts

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#7]
## 💰 Feature

User can like posts

## 🗒️ Notes

This will require me to make a POST route, a DELETE route and a GET route to have a functioning like button

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030555-e8a73e80-4510-11eb-9dd3-6749ee242d1e.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/api/likes/post/:postId`.
- [x]  Create a route in `server/index.js` to handle DELETE requests at `/api/likes/post/:postId`.
- [x] Create a route in `server/index.js` to handle GET requests at `/api/likes/post/:postId`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server for the post request.
- [x] Refactor the component to fetch the data from the server for delete requests.
- [x] Complete the component with an initial state of likes and an event handler for handleLikeClick
