### ISSUE TITLE
Users can comment on posts

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#8]
## 💰 Feature

User can comment on a post

## 🗒️ Notes

This will require me to keep track of the user writing the comment and render the appropriate comments for each post.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030612-01175900-4511-11eb-969f-24513093387b.png)
![image](https://user-images.githubusercontent.com/71475689/103030657-19877380-4511-11eb-81fb-908058056306.png)

## ✅ Tasks

- [x] Create a route in `server/index.js` to handle POST requests at `/api/comments`.
            - [ ] within the body have: username, userId and postId
- [x] Create a route in `server/index.js` to handle GET requests at `/api/comments`.
- [x] Test the route with HTTPie.
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Complete the component with an initial state of this.state.comments and an event handler for handleComment
