### ISSUE TITLE
Users can filter all posts by tag

### ISSUE THREAD

**Issue by Jazzmine-Jimenez** [Jazzmine-Jimenez/EarthSpace#9]
## 💰 Feature

User can ...

## 🗒️ Notes

This will require me to ...

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/71475689/103030727-36bc4200-4511-11eb-9d42-8992b3df2da7.png)

## ✅ Tasks

- [ ] Create a route in `server/index.js` to handle POST requests at `/api/flashcards`.
- [ ] Test the route with HTTPie.
- [ ] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [ ] Refactor the component to fetch the data from the server.
- [ ] Complete the component with an initial state of ... and an event handler for ...
